name: Build
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Restore 
      run: nuget restore .\Project\EveryoneIsJohnTracker.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: .\Project
      run: msbuild EveryoneIsJohnTracker.sln
